# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- main

pool:
  name: BruhArmyTesting

variables:
  programPath: 'C:\Program Files\Kamino'

steps:
- script: |
    git clone https://github.com/dbaseqp/bruharmy/ C:\bruharmy\
  displayName: 'Pull src from Github'

- powershell: |
    Stop-Service -Name 'Kamino'
    go build -o '$(programPath)'
    cp .\assets\ '$(programPath)' -Recurse -Force
    cp .\lib\ '$(programPath)' -Recurse -Force
  displayName: 'Build executable, move assets and lib'

- powershell: |
    rm "C:\Program Files\WindowsPowerShell\Modules\BruhArmy" -Recurse -Force
    Install-Module BruhArmy -Force
  displayName: 'Install Latest BruhArmy module'

- powershell: |
    Start-Service -Name 'Kamino'
  displayName: 'Start Kamino service'

- powershell: |
    rm 'C:\bruharmy' -Recurse -Force
  displayName: 'Cleanup'