# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- main

pool:
  name: BruhArmyTesting

variables:
  workingPath: 'C:\agent\_work'
  programPath: 'C:\Program Files\Kamino'

steps:
- script: |
    git clone https://github.com/dbaseqp/bruharmy/
  workingDirectory: '$(workingPath)'
  displayName: 'Pull src from Github'

- script: |
    go build -o '$(programPath)'
    cp .\assets\ '$(programPath)' -Recurse
    cp .\lib\ '$(programPath)' -Recurse
  workingDirectory: '$(workingPath)\bruharmy'
  displayName: 'Build executable, move assets and lib'
