# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- main

pool:
  name: BruhArmyTesting

variables:
  workingPath: 'C:'
  programPath: 'C:\Program Files\Kamino'

steps:
- script: |
    powershell.exe -c "pwd"
    powershell.exe -c 'git clone https://github.com/dbaseqp/bruharmy/ C:\bruharmy\'
  workingDirectory: '$(workingPath)'
  displayName: 'Pull src from Github'

- script: |
    powershell.exe -c "pwd"
    powershell.exe -c "go build -o '$(programPath)'"
    powershell.exe -c "cp .\assets\ '$(programPath)' -Recurse"
    powershell.exe -c "cp .\lib\ '$(programPath)' -Recurse"
  workingDirectory: '$(workingPath)\bruharmy'
  displayName: 'Build executable, move assets and lib'
